[package]
name = "acc"
version = "0.1.0"
authors = ["hatoo <hato2000@gmail.com>"]

[dependencies]
termion = "1.5"
unicode-width = "0.1"
clap = "2.3"
syntect = "2.1"
shellexpand = "1.0"
dirs = "1"
config = "0.9"
serde = "1"
serde_json = "1"
serde_derive = "1"