[file-default]
indent_width = 4

[file.rs]
compiler = { command=["rustc", "$FileName$"], type="rustc" }
lsp = ["rls"]
formatter = ["rustfmt"]

[file.cpp]
# Respect clang-format
indent_width = 2
lsp = ["clangd"]
formatter = ["clang-format"]
